langage: node_js
version: 
  - "8"
dist: trusty
os:
  - linux
  - osx
env:
  -NODE_ENV=ci
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test